### ISSUE TITLE
Windows Defender finds a trojan in the binary of release v0.2.0

### ISSUE THREAD

**Issue by doppioslash** [Snoothy/UCR#1]
See screenshot:
![virus](https://user-images.githubusercontent.com/508324/35417329-d780db70-0224-11e8-8742-013e6758cdf5.PNG)

**Comment by Snoothy** [comment]
This is a false positive from Windows Defender. You can see a VirusTotal scan here:
https://www.virustotal.com/#/url/a0e6f27a01c86240ab3f80452b35d2877a0079c6706656cfb344b6c5a6867b61/detection

Windows Defender sometimes even give false positives based on files names, it is unfortunately a common problem
