### ISSUE TITLE
Mouse Movement to analog stick?

### ISSUE THREAD

**Issue by permastun** [Snoothy/UCR#10]
Is this even possible? I have Interception installed but there is no axis for mapping the mouse movement to RX+RY. Am I overlooking something?

I'm trying to fully emulate the DS4 with mouse and keyboard for use with PS Now(game streaming service.) I have a disability and can't use a regular DS4. Any help would be greatly appreciated.

**Comment by Snoothy** [comment]
This is a planned feature which this version unfortunately does not currently support. However, this feature is prioritized to one of the next releases

**Comment by evilC** [comment]
Implemented in 0.4.0

**Comment by hannsen** [comment]
Is there supposed to be an axis to select for the mouse device?

Whenever I click on the 3 dot menu right nothing happens

![image](https://user-images.githubusercontent.com/3775136/71079448-96a83c00-218b-11ea-8a31-5fac63b6683b.png)

**Comment by Chiggy-Playz** [comment]
@hannsen did you get it to work?

**Comment by evilC** [comment]
Use the DeltaToAxis plugin from the [UCR-Plugins](https://github.com/HidWizards/UCR-Plugins) pack

**Comment by hannsen** [comment]
Yes works with the Plugins, thanks

**Comment by hannsen** [comment]
It should be added to this page that you need the plugin for mouse movements:

https://github.com/snoothy/ucr/wiki/Core_Interception
