### ISSUE TITLE
Can't activate profile

### ISSUE THREAD

**Issue by Dilolaft** [Snoothy/UCR#102]
Its always not responding, and after that i just can't close this program, even using task manager (windows 7)
[2019-06-16.log](https://github.com/Snoothy/UCR/files/3294377/2019-06-16.log)

**Comment by evilC** [comment]
I don't see any evidence of subscribing to an input device in that log  
Screenshot of plugin?

**Comment by Snoothy** [comment]
It looks like you used an old unsupported context.xml. Please try again with a new context by moving or deleting the context.xml. Some problems with bindmode will be resolved in v0.8.0
