### ISSUE TITLE
Can it support Combination keys

### ISSUE THREAD

**Issue by neroeggs** [Snoothy/UCR#109]
Can it support Combination keys?How to Combine Multi-key Mapping

**Comment by neroeggs** [comment]
like ctrl+w ？

**Comment by Snoothy** [comment]
The current v0.7.0 has limited support as described in #100, however, states are deprecated from v0.8.0. A later feature is planned to better support multiple modifiers

**Comment by dburongarcia** [comment]
Hi, in v0.8.0 I managed to create several combinations just adding an extra plugin (button to button) to a mapping, It works with all modifiers.
