### ISSUE TITLE
Bind button triggers on release event, not press event

### ISSUE THREAD

**Issue by evilC** [Snoothy/UCR#112]
Repro 1:  
Move mouse cursor over Bind button  
Press and hold left mouse - At this point, Bind mode is not triggered  
Release mouse - Bind mode is triggered at this point  
Press and hold left mouse - Bind Mode binds to Left Mouse  
Release Left Mouse while cursor still over Bind Mode button - Bind Mode is re-triggered  

Expected Behavior 1: 
Move mouse cursor over Bind button  
Press and hold left mouse - Bind mode is triggered  
Release mouse - left mouse is not bound, as Bind Mode only responds to press events  
Press and hold left mouse - Bind Mode binds to Left Mouse  
Release Left Mouse while cursor still over Bind Mode button - nothing happens    

Repro 2:  
Click Bind Mode button  
Press and hold Space - Space is bound  
Release Space - Bind Mode is re-triggered  

Expected Behavior 2:
Click Bind Mode button  
Press and hold Space - Space is bound  
Release Space - Nothing happens

Resolution:  
Make the Bind Mode button only respond to press events, not release events

**Comment by Snoothy** [comment]
Fixed by #113
