### ISSUE TITLE
vJoy 4-direction POV not found

### ISSUE THREAD

**Issue by juanitogan** [Snoothy/UCR#115]
Create a vJoy device with a "4 Directions" POV and I can see the POV in Windows' Game Controller properties.

In UCR, however, I can't find any POVs to map a button to on the same vJoy device.

Switch that vJoy POV to a "Continuous" POV and then I can see a POV to map to in UCR.

Also, this took a while to find because, with no POV recognized, the POV menu disappears and it is then not apparent how to map a POV if you've never used this tool before with a POV.  It would be more informative if the POV menu always remained even if no POVs are found (just say "none found" or something like that on the submenu).  Without that UI help, I was first assuming that POVs aren't supported yet... which didn't make much sense... so I kept digging and finally found the problem.

**Comment by evilC** [comment]
Seems to work fine, did you reboot after switching to Discrete POV?  
![](https://i.imgur.com/dq4vRNC.png)

**Comment by Snoothy** [comment]
I did not. It seems to have been a vJoy configuration issue

**Comment by juanitogan** [comment]
I doubt I tried a reboot but don't recall for sure.  It would not have seemed needed given that Windows' Game Controller responds to the setting.
