### ISSUE TITLE
Can't read LT/RT from Xbox One controller?

### ISSUE THREAD

**Issue by pmjm** [Snoothy/UCR#117]
I'm trying to remap the RT on my xbox one controller to a key on the keyboard. I've tried Button to Button and Axis to Button and neither approach detects the RT press from the Xbox One controller.

Is this a bug? Thanks in advance.

**Comment by NokiaN73** [comment]
My xbox 360 controller too cant read LT and RT. How you bind L3 and R3?

**Comment by Snoothy** [comment]
The trigger is analog which means you need to to use `Axis to Button` if you want to remap the trigger to a button
