### ISSUE TITLE
Can this be used to emulate a bluetooth controller?

### ISSUE THREAD

**Issue by 7osCraft** [Snoothy/UCR#118]
Hello,
  I was looking for a way to use my keyboard and mouse as a controller for the ps4 or xbox.
I found UCR which allowed me to map my keyboard and mouse to a vitural controller.
But how can I make my pc broadcast this controller over bluetooth to use in a console?

**Comment by evilC** [comment]
Dunno of any way to do it via BlueTooth, but UCR supports the [Titan One](https://www.consoletuner.com) device, which can be used to send input to a playstation.  
Doesn't the PS4 require controller auth tho? They are making a new Titan Two with a 2nd input so you can plug in a real controller for the PS4 to auth against, but there is no API for it yet, so we cannot support it
