### ISSUE TITLE
Profile can't be activated

### ISSUE THREAD

**Issue by sigmatc24** [Snoothy/UCR#120]
Hello,

I'm trying to bind an xbox one controller to a PS4 controller to be able to use PS4 TouchPad 

I did all the bindings. saved the profile but when I click on activate profile. I have the following message as you can see in this screenshot

![UCR_Profile_error](https://user-images.githubusercontent.com/48797609/66718498-89ae4b80-eddc-11e9-9476-242fdd0d0e65.jpg)

Any ideas what is wrong ?

**Comment by Snoothy** [comment]
It is usually problems with your ViGEm installation, try (re)installing it

**Comment by sigmatc24** [comment]
Can you please send the link to a version compatible with your program (the one you are using will be perfect) because I don't have any ViGEm at all installed on my pc !!

Cheers :)

**Comment by Snoothy** [comment]
Please read the Wiki: https://github.com/Snoothy/UCR/wiki/Installation-and-Setup

**Comment by sigmatc24** [comment]
Alright thanks it was ViGem Setup which was missing :)
