### ISSUE TITLE
Activating a child profile only activates mappings from its parent

### ISSUE THREAD

**Issue by saurabhseth** [Snoothy/UCR#121]
When the child profile is activated, the mappings in the child profile do not work. Only the ones from the parent work.

I took a look at the code and will submit a pull request with a fix.

**Comment by Snoothy** [comment]
Thanks. I am currently writing a new feature in the subscription manager, I'll make sure to have this fixed, too

**Comment by Snoothy** [comment]
This is fixed by #127
