### ISSUE TITLE
WiFi HID emulator

### ISSUE THREAD

**Issue by mkeyno** [Snoothy/UCR#13]
hi , sorry to open a ticket for my question, but I have a question that may related to your field of repository and any possible hint really appreciated
Actually I interested to send game-pad data by WiFi bridge(ESP8266) to my laptop, but generic joystick only use USB port, Is there a way to emulate "HID-compliant game controller" driver which listen to IP message instead of USB port
Tnx

**Comment by Snoothy** [comment]
You should take a look at https://virtualhere.com/cloud it allows you to use a [TP-Link TL-MR3020 V1 mini (router)](https://www.virtualhere.com/hardware) to make any USB device wireless. Using a ESP8266 would require you to implement a receiver as well which emulates HID device or build some software to parse your WiFi messages
