### ISSUE TITLE
ERROR Failed to activate profile successfully 

### ISSUE THREAD

**Issue by EnduringGuerila** [Snoothy/UCR#134]
Halo Reach PC Forge can be enabled but it requires a controller. 
I am attempting to assign the  'C'  key on my keyboard to xbox D-Pad Up
I installed the Interception plugin to enable my keyboard as an input device and set ViGEm Xbox 360 Controller 1 as my output device. 

I only made one Button to Button remap; Keys, C to DPad, Up.

log: 

> 2019-12-08 18:47:35.3067 INFO Launching UCR 
> 2019-12-08 18:47:37.4070 ERROR Failed to load context.xml 
> 2019-12-08 18:47:37.8120 DEBUG Start bind mode 
> 2019-12-08 18:52:14.0924 INFO Launching UCR 
> 2019-12-08 18:52:16.5877 DEBUG Start bind mode 
> 2019-12-08 18:53:14.8860 DEBUG Activating profile: {HaloForge} 
> 2019-12-08 18:53:14.8860 DEBUG Successfully populated subscription state 
> 2019-12-08 18:53:14.8860 DEBUG Subscribing output device: {Device:{ViGEm Xbox 360 Controller 1} Provider:{Core_ViGEm} Handle:{xb360} Num:{0}} 
> 2019-12-08 18:53:14.9029 ERROR Failed to activate profile successfully

**Comment by Snoothy** [comment]
You have not installed ViGEm, please follow the instructions on the Wiki
