### ISSUE TITLE
Controller vibration not working when emulating xbox360 to ds4

### ISSUE THREAD

**Issue by pamilaa** [Snoothy/UCR#135]
Hey, not sure if this is a bug/deficiency of ucr, vigem or sharpdx.

Anyway I was able to bind all the buttons and everything except vibration is working correctly. It is working natively when testing, but not when emulating ds4 controller.

I was using https://html5gamepad.com/ to test the emulation and the native feedback. When using the vibration test in native mode it works, but not in emulated mode as expected.

I noticed that the wiki page says that force feedback is not supported, but wasn't sure if it was referring to the vibration or force feedback of wheels.

![image](https://user-images.githubusercontent.com/55771456/70860563-eab4e580-1f2b-11ea-92b4-0f715027a2ad.png)

**Comment by Snoothy** [comment]
Vibration/Force feedback passthrough is a wish list feature which is missing to many pieces to be implemented any time soon, unfortunately. Support in drivers and providers might make this feasible in the future

**Comment by goatandsheep** [comment]
ViGEm now has added rumble

```cs
controller.FeedbackReceived += new Xbox360FeedbackReceivedEventHandler(FeedbackEventHandler);
```
If I place a bounty on this can we expedite this or can I collaborate?

**Comment by cyberluke** [comment]
Hi, any update on FFB forwarding from UCR to vJoy, please?

**Comment by l0oo** [comment]
Hello!
Any news about FFB forwarding?

**Comment by achira-kati** [comment]
@l0oo You can try this: [https://github.com/achira-kati/IOWrapper](https://github.com/achira-kati/IOWrapper). I was able to forward FFB from ViGEm Xbox 360 Controller to my Xbox Controller, I still haven't tried DS4, btw.

<img width="517" height="241" alt="Image" src="https://github.com/user-attachments/assets/74cfe2f2-d6ae-44ad-b3de-e1e20d87fa17" />
