### ISSUE TITLE
Click to bind "crashes", make UCR unresponsive or doesn't work

### ISSUE THREAD

**Issue by dburongarcia** [Snoothy/UCR#138]
Hello, using the Delta to Axis, the Input "Click to bind" with a second mouse makes the mouse click of the first mouse unresponsive in just UCR. The only way to edit the bind is selecting it from the list.

On the other hand, in Button to Button, the Output "Click to bind" doesn't work. You have to select each button or key, and that's really tedious because there is no autocomplete or sorting system, you have to scroll through every possible key.

**Comment by evilC** [comment]
The crashing in Bind Mode is a known issue with 0.8.0, and should be addressed in the upcoming release, which hopefully should be this weekend

**Comment by dburongarcia** [comment]
Great. What about the Output "Click to bind"? Right now it takes forever to map a whole keyboard. Thanks

**Comment by Snoothy** [comment]
This should be fixed with the v0.9.0 release

**Comment by ShunoJunsu** [comment]
Me too
