### ISSUE TITLE
Tips to create a secondary simultaneous keyboard for different windows

### ISSUE THREAD

**Issue by dburongarcia** [Snoothy/UCR#139]
Using AHK and LUAMacros some time ago I wrote a script to make each keyboard send keystrokes to different windows in the background (visible but not in focus) I wonder if there is any way to make the same with UCR, combining it or not with AHK. I'm thinking about these options:

1. Adding a modifier to every key I needed and make the programs read only the keys with modifier (tedious and not suitable for many programs)
2. The AHK version of UCR, but it's older and it has problems with vJoy (although I have the latest version of vJoy installed, it says "the relevant registry entries could not be found, install the last version of vJoy")
3. Using yours AHI https://github.com/evilC/AutoHotInterception but I am not sure if UCR and AHI can use Interception at the same time.

Thank you

**Comment by evilC** [comment]
You could do the whole thing with like a 10-line AHI script  
Just use `SubscribeKeyboard` to subscribe to all keys on the secondary keyboard, then `ControlSend` each key to the desired window
