### ISSUE TITLE
Saving profile issue

### ISSUE THREAD

**Issue by shnevan** [Snoothy/UCR#140]
When I hit to save my profile the program closes then when I open it back up it's blank and there aren't any profiles there.

**Comment by Snoothy** [comment]
Please state which version you are using and upload the latest log file from the logs folder. If you have more steps of what you have done please provide those as well

**Comment by Axelpop** [comment]
I’ve been using the app for a few days i can’t believe you created something so amazing ,i don’t know what to say, thanks for this app, it changed the way i play my favorite games sony...

**Comment by hannsen** [comment]
@Axelpop https://github.com/Snoothy/UCR/wiki/Core_Interception

**Comment by Axelpop** [comment]
I did the procedure but do not understand what should happen,I think I should see the mouse and keyboard on UCR as an input device ? It doesn’t happen, I don’t understand, you can explain to me...it would be perfect if I could also play with muses and keyboard.

**Comment by hannsen** [comment]
Yes it should appear as an input device.

The folder in UCR is not relevant, you need to follow the install instructions for interception. If it doesn't show afterwards I can't help you

**Comment by Axelpop** [comment]
@hannsen @Snoothy Thank you so much for your help!!! I don’t know why the app didn’t see mouse and keyboard until I physically disconnected and reconnected the two devices,if before the application was amazing,now it is even more so.Thanks for everything!!!!!!!
