### ISSUE TITLE
Unable to load DLL 'vigemclient.dll'

### ISSUE THREAD

**Issue by celezar** [Snoothy/UCR#149]
After installing the latest version of ViGEm (1.16.116) UCR fails to start. Here is the log

`FATAL Unable to load DLL 'vigemclient.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) System.DllNotFoundException: Unable to load DLL 'vigemclient.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Nefarius.ViGEm.Client.ViGEmClient.vigem_disconnect(IntPtr vigem)
   at Nefarius.ViGEm.Client.ViGEmClient.Dispose(Boolean disposing)
   at Nefarius.ViGEm.Client.ViGEmClient.Finalize()`

**Comment by ZeDeedIsDone** [comment]
This was the response last time -.-
https://github.com/Snoothy/UCR/issues/86

Still have no idea how to "install it right".

Tried:

1.  Reinstalling Windows 10
2.  Reinstalling ViGEm Bus Driver
Same result.

HOWEVER, if I uninstall ViGEm I get this message
`To complete the removal of ROOT\SYSTEM\0001 the system requires a reboot. The setup will end now. Please restart your machine and run setup again.`
![Capture](https://user-images.githubusercontent.com/52952843/74330032-e5f59c00-4dcb-11ea-9b03-42d00b1f4f68.PNG)
At this point I can open UCR_0.9.0 (0.8.0 shows the same vigemclient.dll eror), but the providers don't work, just Core_Midi.
Note: ViGEm Bus Driver is still listed as installed in Apps and Programs.

If I follow the instruction above, and run the uninstaller again, then reinstall we come full circle where it doesn't work.

Edit:
### THE FIX
https://www.microsoft.com/en-us/download/details.aspx?id=52685
I installed both x86 and x64. Not sure if both are necessary.

**Comment by TedThompson** [comment]
This problem still exists, and I have the 2 redist packages at https://www.microsoft.com/en-us/download/details.aspx?id=52685 already installed on my system.

The links to ViGEm in readme.md are broken too - older versions that I can find of ViGEm are also not solving it.

Perhaps ViGEm has been refactored?

**Comment by yipisaias** [comment]
I've managed to solve by installing all the vcredists from here: [https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/). Not sure which version did the trick (maybe 2013?)
