### ISSUE TITLE
Main GUI launch mode

### ISSUE THREAD

**Issue by matteocedroni** [Snoothy/UCR#150]
First of all I want to thank you for such great program!
It is powerful and well done.

It would be useful to be able to start UCR without main GUI (hidden GUI), at logon.
In this way users can simply switch/enable/disable already configured profile through game launch script, with same running UCR.exe. No slow first launch or popping up GUI.

Thanks a lot for your work

**Comment by Snoothy** [comment]
This will be fixed with the v0.10.0 release
