### ISSUE TITLE
Getting started is very confusing

### ISSUE THREAD

**Issue by PortableGoogle** [Snoothy/UCR#156]
The Wiki is very confusing for a new person who just installed it. It says all these core providers come with it, says they need to be setup, but when you go to them they talk about how to install it but the files aren't there. There is just a bunch of dlls but not the exe to install any of the providers. Are the files included actually useless and you still have to download the providers separate? Basically the getting started documentation appears to be dated or something.

**Comment by PortableGoogle** [comment]
I have figure out that yes, the files included in the download for the providers are not for users and that the confusing directions should state that core providers are not actually downloaded. 
I figured out where i got confused, on https://github.com/Snoothy/UCR/wiki/Core-Providers it says that it "ships" with core providers, with in normal business would mean they are included.

**Comment by Snoothy** [comment]
The Wiki is up to date, please start here: https://github.com/Snoothy/UCR/wiki/Installation-and-Setup
