### ISSUE TITLE
Delta axis mouse missing

### ISSUE THREAD

**Issue by PortableGoogle** [Snoothy/UCR#157]
It seems to say that you added delta axis to map a mouse to a joystick back in .4, but after installing the providers there is axis to axis, button to axis but there is no option for delta axis at all anywhere. If this is the wrong place, Sorry but couldn't find anywhere else to try and message problems

**Comment by WelpThatWorked** [comment]
As specified in the Readme, these plugins reside in https://github.com/HidWizards/UCR-Plugins

**Comment by PortableGoogle** [comment]
Thank you, I read it but completely missed it would be in there lol.
