### ISSUE TITLE
UCR doesn't accept enabling new profiles while minimized to tray (develop branch)

### ISSUE THREAD

**Issue by LurkerCoder** [Snoothy/UCR#160]
While the application is minimized to the tray, it is unable to receive requests for activating profiles (the same way it would if it was opened). i.e.: running UCR.exe -p MyProfile2 while UCR is already running and minimized to tray will not apply MyProfile2.

This is running a manual build of the latest develop branch.

**Comment by WelpThatWorked** [comment]
This is because when the main window is hidden, it looses it's window handle and thus it cannot transfer the arguments as the SendMessage function requires a window handle

**Comment by LurkerCoder** [comment]
I was really excited about the tray stuff, but I also need to be able to start/stop through external means.

I'm not much of a C# developer, but I've done single-instance communication in VB using named pipe. 

I'll leave this here just in case: https://github.com/AutoItConsulting/examples-csharp/tree/master/MutexSingleInstanceAndNamedPipe
