### ISSUE TITLE
Trigger Buttons

### ISSUE THREAD

**Issue by Gogonemnem** [Snoothy/UCR#167]
The left/right trigger buttons need to be range -100 to 100 instead of 0 to 100 for a pressed button. A change to 0 to 100 for a whole press and 50 to 100 for a half press would be nice/less confusing

**Comment by evilC** [comment]
Not going to happen. For XInput, sure, you know which axes are triggers and which are not, but for DirectInput (eg DS4 controllers), there is no way of knowing what the resting point of an axis is
