### ISSUE TITLE
remap Cypress Withehome remote control power off button

### ISSUE THREAD

**Issue by vothar** [Snoothy/UCR#172]
hello,
i use a 'china' IR remote controller Cypress withehome on my system. i can remap all butons with the 'interception' module, apart one that is the 'power off' button... this one is not in the keyboard command and i don't know how to intercept this event as this button drive a silent shutdown of the computer.

Can you help ?

thanks

**Comment by Snoothy** [comment]
This is not a problem with UCR. We show all available buttons from interception and if it is missing, then it is not supported by interception
