### ISSUE TITLE
Mouse to controller mapping

### ISSUE THREAD

**Issue by Netherquark** [Snoothy/UCR#180]
How to enable mouse to controller axis mapping?
Even better, could you integrate virtual keyboard and mouse declaration, like the already present virtual controller declaration? Nothing complicated, just basic keyboard and mouse.

**Comment by WelpThatWorked** [comment]
For delta to axis mapping (mouse to controller axis) you need the plugin from the [UCR-Plugins Repository](https://github.com/HidWizards/UCR-Plugins).

**Comment by Impr0ve** [comment]
when I map anything UCR freezes and I have to use task manager has anybody else had this problem?

**Comment by jkeynes7** [comment]
> when I map anything UCR freezes and I have to use task manager has anybody else had this problem?
Impr0ve, l had the same problem until l deleted the DS4Windows folder in the Providers folder. Tho it worked at the third l was trying to set a mapping, so have patience

**Comment by jgumielazal** [comment]
> 
> 
> when I map anything UCR freezes and I have to use task manager has anybody else had this problem?

l had the same problem until l deleted the DS4Windows folder in the Providers folder. Tho it worked at the third l was trying to set a mapping, so have patience and keep trying
