### ISSUE TITLE
Suggestion: smoothing keyboard input

### ISSUE THREAD

**Issue by winkerbie** [Snoothy/UCR#183]
When I map keys (e.g. left and right arrow) to a joystick axis the deflection goes from 0-100% immediately. 

It would be good if the code did smoother transition between 0-100, otherwise, it creates harsh turns in some games.

Will this be possible, please?

**Comment by WelpThatWorked** [comment]
This plugin should do what you want. Unzip, paste the DLL into the UCR\Plugins\UCR.Plugins folder and run the unblock utility. Tell me if you have any issues.

[ButtonsToAxisRamp.zip](https://github.com/Snoothy/UCR/files/4922538/ButtonsToAxisRamp.zip)

**Comment by winkerbie** [comment]
works really well, thanks alot
