### ISSUE TITLE
make software think my mouse and keyboard are a controller?

### ISSUE THREAD

**Issue by 0lm** [Snoothy/UCR#185]
hi
is there a way to make a software think that my mouse+keyboard is a controller? i am playing some very old games on an emulator, and i suck at aiming with an analog stick (like, imagine playing counterstrike with a controller. some might good at it, some suck hard and prefer a mouse). and i suck with counterllers when it comes to games which are counterstrike-like (regarding aiming stuff). so, is there a way to remap my mouse, so emulators will think that it is an analog stick?

i know there are enough remappers that allow to remap keyboard and mouse actions on controllers, so your cojntroller will work like a mouse or keyboard. but i want the opposite. i want emulators to think that my keyboard and mouse are actually the controller. i know i can remap buttons to my keyboard with emulators, but i never found a feature to remap an analog stick on my mouse movement. (example emulators i am talking about: m64p (a version of mupen64plus.) or porhect64)

**Comment by WelpThatWorked** [comment]
you want the DeltaToAxis plugin from [the extra plugins repository](https://github.com/HidWizards/UCR-Plugins)

**Comment by 0lm** [comment]
Wait there are also Plugins for UCR? I did not know that. Thanks for showing me!

**Comment by 0lm** [comment]
looks like i got another problem now. somehow i cant even add keyboards or mouses as input devices. they just dont exist in the list.

**Comment by 0lm** [comment]
i guess i encountered a bigger problem now. although i installed interception now, it wont recognize my mouse in the UCR list of input or output devices.
besides, i have to use fireshock + shibari since it is a dualshock 3 controller. i at least tried to remap keyboard keys on my controller but it didnt work either. when clicking my controller buttons, it didnt write any remapped letters. i am not sure what i am doing wrong.
