### ISSUE TITLE
Unable to capture steam controller keyboard output with interception

### ISSUE THREAD

**Issue by mtwomey** [Snoothy/UCR#188]
I'd like to be able to capture the output of the steam controller's keyboard mode in order to do some remapping with UCR. It doesn't appear that it's currently possible to intercept this with interception, but looking for confirmation of that or a workaround.

In other words, capture this: 
![image](https://user-images.githubusercontent.com/7715262/91486861-78462480-e872-11ea-9974-2b012f29c8b0.png)

**Comment by evilC** [comment]
Interception only captures input coming from physical devices - the steam controller will be sending the input from software, not hardware, so will be unsupported
