### ISSUE TITLE
No keyboard/mouse in devices list

### ISSUE THREAD

**Issue by Ariloum** [Snoothy/UCR#191]
Is it a bug or this tool isn't support other HID devices except audio/midi/joystick?
I need to map some keys to virtual joystick controller but there is no keyboard in the list...

**Comment by Ariloum** [comment]
https://pasteboard.co/JqbxLUc.jpg
https://pasteboard.co/JqbxWPn.jpg

**Comment by WelpThatWorked** [comment]
Read the manual, install interception.

**Comment by Ariloum** [comment]
It works with interception, thanks
