### ISSUE TITLE
Keyboard blocking not working

### ISSUE THREAD

**Issue by pauliliesi** [Snoothy/UCR#193]
Blocking does not seem to take effect.

* Intercept installed and working in UCR
* Value set to "True" in settings.xml in the UCR intercept providers folder
 Is there something I am missing?

**Comment by pauliliesi** [comment]
This is my file

`<?xml version="1.0" encoding="utf-8" ?>
<Settings>
  <Setting>
    <Name>BlockingEnabled</Name>
    <Value>true</Value>
  </Setting>
  <Setting>
    <Name>PollRate</Name>
    <Value>10</Value>
  </Setting>
  <Setting>
    <Name>StrokeOnThread</Name>
    <Value>false</Value>
  </Setting>
</Settings>`

**Comment by Snoothy** [comment]
Did you also flip the "Block" switch for your binding?

**Comment by pphenric** [comment]
That has done it. Sorry for being a newbie. Is there also a way to map the stick button PRESS? I don't see any

**Comment by pauliliesi** [comment]
Thank you! That has done it. Sorry for being a newbie
