### ISSUE TITLE
Triggers constantly being held halfway down

### ISSUE THREAD

**Issue by reageer** [Snoothy/UCR#196]
I'm using UCR with Interception to emulate an Xbox 360 controller, this used to work fine until now.

Whenever anything is mapped to either the left or the right trigger (Button to Axis); both triggers will constantly be held halfway down. When pressing the button that is mapped to the trigger, the trigger will be pressed all the way down, but when that button is released; it'll go back to being held halfway down again.

The only way to release the trigger is to map a button to the High state of the trigger using the Button**s** to Axis plugin. But that only works as long as that button is pressed.

Sometimes there's also no indication of the triggers being pressed (when testing with gamepad-tester.com), even though they still are in-game. When this is happening, the triggers also aren't responsive.

I tried about everything I could think of, there's also no errors in logs.

**Comment by evilC** [comment]
Set Press to 100, Release to -100
