### ISSUE TITLE
Running in background

### ISSUE THREAD

**Issue by Netherquark** [Snoothy/UCR#197]
I noticed that once the UCR window is closed, the program closes. Could you provide an option so that instead of closing the program, it will get minimised to the action/program tray. Also, I manually configured the app to run on startup, but an option of having it run on startup would be nice too. As of now if I want the program running but not interfering as a window I have to keep it in a different virtual desktop.

**Comment by superuser7777** [comment]
There is software that stores the program in the taskbar in a non-resident type.
https://github.com/kimbos/PinToTaskbar

I use SmartSystemMenu.
https://github.com/AlexanderPro/SmartSystemMenu
