### ISSUE TITLE
Uninstalling UCR

### ISSUE THREAD

**Issue by Shaun-v1** [Snoothy/UCR#203]
Uninstalling UCR from a PC, Need help.
If I uninstall interception from command prompt and delete all the UCR and Interception files, does that mean I have completely uninstalled UCR and Interception or do I need to execute an Uninstall file(which apparently didn't exist in the folder).

Label : help wanted

**Comment by WelpThatWorked** [comment]
Yes, UCR does not create any files outside of it's base directory, so deleting the folder is all that is necessary.
