### ISSUE TITLE
Unable to open UCR

### ISSUE THREAD

**Issue by chonglebonk** [Snoothy/UCR#216]
Hi! Sorry if this is obvious or not the right place to post this, I'm new to computery stuff and Github and not entirely sure what I'm doing. I've downloaded and unzipped UCR and read the directions. They say to open ucr.exe, but I search the folder and nothing comes up. I tried downloading the .ahk version and it doesn't have one either. Am I being stupid and missing something? I'd be happy to provide more info if you need it. Thanks!

**Comment by WelpThatWorked** [comment]
Could you post a screenshot of the unzipped folder in your file explorer?

**Comment by chonglebonk** [comment]
![ucr-issues](https://user-images.githubusercontent.com/79812175/109436338-9ab52800-79e4-11eb-924f-0d059b80228e.PNG)

Here it is.

**Comment by WelpThatWorked** [comment]
Ah, that's the source code, you want to download a [release build](https://github.com/Snoothy/UCR/releases)

**Comment by chonglebonk** [comment]
Oh yeah that would do it lol. Thanks!

**Comment by evilC** [comment]
@chonglebonk @WelpThatWorked that's the source code of [UCR-AHK](https://github.com/evilC/UCR) (A completely different application)
