### ISSUE TITLE
Button to Axis value?

### ISSUE THREAD

**Issue by Serj-Lewa** [Snoothy/UCR#221]
Hello. I would like to make such binding: button hit to an axis value. For example left mouse button click sets X Axis to 10%. Is it possible in the current version of UCR?

**Comment by evilC** [comment]
Yes, just use the `Axis when Presssed` and `Axis on Release` boxes
![image](https://user-images.githubusercontent.com/1719428/110643595-29c3fc00-81ac-11eb-878c-3b27e54883d5.png)
