### ISSUE TITLE
24 bit audio output on Raspberry Pi 4 b model

### ISSUE THREAD

**Issue by CoppolaVH** [Snoothy/UCR#223]
I am looking for options to stream 24 bit output over HDMI to my AVR.

Currently my pi downsamples to 16 bit.   

What is the solution to output at 24 bit on the pi, please.

**Comment by evilC** [comment]
Eh? I have absolutely no idea what you are talking about - this is a windows application and won't run on an rPi?
It's also absolutely nothing to do with Audio

**Comment by CoppolaVH** [comment]
No, this is a Raspberry pi issue as although I am able to send 24 bit files to it via a Linux application, the pi downsamples it to 16 bit.

**Comment by evilC** [comment]
What does UCR (A windows application for manipulating keyboard, mouse and joysticks) have to do with raspberry pis and audio?

**Comment by CoppolaVH** [comment]
I did not say anything about UCR.    I am running Moode Audio and streaming 24 bit FLAC files to a Raspberry PI 4 b model.  The pi downsamples the audio from 24 bit to 16 bit.

**Comment by CoppolaVH** [comment]
Over HDMI that is.

**Comment by evilC** [comment]
This issue is on the UCR issue tracker, so inherently you are saying something about UCR ?!?!

**Comment by CoppolaVH** [comment]
Oh, sorry, I am new to github!!

**Comment by evilC** [comment]
Closing as I guess you were posting in the wrong place
