### ISSUE TITLE
External Numpad still writes Numbers (standard keypresses)

### ISSUE THREAD

**Issue by NicciZar** [Snoothy/UCR#233]
I am using a secondary Numpad for Hotkeys and I remapped a key to do something different.
When testing the key I noticed that it still pasted its standard character inside Editor

I bound the key "1" from secondary device Numpad to "F13" of the same Numpad (the numpad just has numbers, no function keys) 
=> tested inside Editor and saw that I can still write 1 with the Numpad
(after binding "1" to "2" it always wrote "12", so It doesn't really catch the key from being written)

I installed Interception Version 1.0.1 and I am using UCR Version 0.9.0 .

Some screenshots:
![image](https://user-images.githubusercontent.com/43537611/115999035-75aaf300-a5ea-11eb-9189-69c41d830edf.png)

![image](https://user-images.githubusercontent.com/43537611/115999057-8c514a00-a5ea-11eb-9ccd-9886ec65a1e6.png)

Best regards

**Comment by WelpThatWorked** [comment]
If you haven't, you will need to [enable blocking](https://github.com/Snoothy/UCR/wiki/Core_Interception#blocking-with-interception).

**Comment by NicciZar** [comment]
Does that block every device or only the devices I put into the UCR Program?

Also do I have to put the Output device to another device as its blocked?

**Comment by WelpThatWorked** [comment]
Only the selected devices are blocked, and it only blocks the original input so you will **not** need to select another output.

**Comment by NicciZar** [comment]
I edited the specific file and set the option to block the key.

Its now working as expected!

Thank you for your help.

Screenshot for reference: (for testing purposes I set the Key to be Number 2!)

![image](https://user-images.githubusercontent.com/43537611/116005303-a13bd680-a606-11eb-9e6f-fc732e4194bf.png)
