### ISSUE TITLE
Wiki edit request - vjoy driver website compromised

### ISSUE THREAD

**Issue by Relvees** [Snoothy/UCR#235]
Following my attempt to install and utilise vJoy within UCR, I'd noticed multiple warnings of malicious software being installed, and (foolishly) continued to install the driver alongside a RAT installed under C:\Users\\<username\>\AppData\Roaming\JCLf5aAc\ctfmon.exe, an [installation of NetSupport Client configured to point to a server under a .cn domain.](https://i.imgur.com/xk2fHjn.png)

It has been confirmed by the original developer that [their website has been compromised](https://vjoy.freeforums.net/thread/194/download-page-404), and advises any users not to use the download links currently specified in this repo's wiki.

The developer advises to download from [the sourceforge releases directly](https://sourceforge.net/projects/vjoystick/), whilst a slightly more recent repository is being [worked on by njz3](https://github.com/njz3/vJoy/releases)

I am unable to make these adjustments to the wiki as a non-committer, but have done so on a fork of this repo.
https://github.com/Relvees/UCR/wiki/Core_vJoyInterfaceWrap

Please amend this to prevent further potential infections

**Comment by evilC** [comment]
Done, thanks for the heads up!
