### ISSUE TITLE
Built in laptop keyboard doesn't work

### ISSUE THREAD

**Issue by zionhian** [Snoothy/UCR#26]
Hi my laptop's built in keyboard doesn't get recognized in the devices core_interception tab. After plugging in a usb keyboard it works. Is this intended or just a bug ?

**Comment by evilC** [comment]
It's currently wired to ignore devices without a VID or PID, or one for which it cannot get a name.  
I made a fix for this last night, but we have not released yet. If you pop into the Discord channel, I can probably give you a DLL which should work.

**Comment by evilC** [comment]
Fixed in 0.4.0
