### ISSUE TITLE
about vJoy pov and Vigem pov

### ISSUE THREAD

**Issue by rayPopo** [Snoothy/UCR#4]
vJoy pov max is 35900 but vigem pov max is 36000. so how to mapper each other ?

**Comment by rayPopo** [comment]
sorry, i fotgot to thank snoothy and evilC to dev this program 👍

**Comment by evilC** [comment]
`vigem pov max is 36000`?  
1) ViGEm itself does not *have* POVs. Specific ViGEm *targets* (eg DS4 or Xbox) have POVs, and they are completely unrelated to each other.  
2) Neither [ViGEm DS4](https://github.com/ViGEm/ViGEm.NET/blob/master/ViGEmClient/Targets/DualShock4/DualShock4Report.cs#L41), nor [ViGEm Xbox360](https://github.com/ViGEm/ViGEm.NET/blob/master/ViGEmClient/Targets/Xbox360/Xbox360Report.cs#L8) use angles (0-360) to set DPad values, they use flags.  

On what are you basing this statement?  Are you talking about how the *output* of a ViGEm device appears to windows?

**Comment by Snoothy** [comment]
Closing until the issue can be reproduced
