### ISSUE TITLE
Unable to open version 0.4

### ISSUE THREAD

**Issue by HyperSlayer72** [Snoothy/UCR#41]
Previously I could open v0.3.1, however it failed to display any devices under my device group manager.  I fixed this by unblocking the zip in the properties context menu then extracting it.  On 0.4 I got the same issue, it opens, no devices are listed.  However when doing the same method of unblocking the zip, it now crashes the moment I try to open. Giving me a generic this application stopped working message. Here is the log.
[2018-10-07.log](https://github.com/Snoothy/UCR/files/2454682/2018-10-07.log)

**Comment by HyperSlayer72** [comment]
Do note that I also tried adding in a context.xml file that I generated with 0.4 (a version I didn't unblock) and get this log. 
[2018-10-08.log](https://github.com/Snoothy/UCR/files/2456936/2018-10-08.log)

**Comment by evilC** [comment]
I personally never do it by unblocking the ZIP itself, I do it by altering the permissions on the files themselves after extracting.  
Try running the following Powershell command as admin in the UCR folder: `Get-ChildItem -Path '.' -Recurse | Unblock-File`

**Comment by evilC** [comment]
Problem was that user had dupe keyboards, and the Interception fix for dupe devices did not make it in to 0.4
