### ISSUE TITLE
Usability suggestions

### ISSUE THREAD

**Issue by spadino** [Snoothy/UCR#53]
- [x] Let user rename mappings
- [ ] Allow to move mappings 
- [ ] Collapsible groups (aka, subfolders) to easily deal with lots of mappings
- [x] Allow users to activate another profile without have to disable the current active profile (auto disabling)
- [x] Minimize to system tray
- [x] Global settings window
- [ ] Refresh button which de-activate and re-activate a profile, from the edit window

**Comment by Snoothy** [comment]
The old profile is already automatically deactivated when activating a new profile

**Comment by evilC** [comment]
Now that you cannot change inputs while a profile is active, I am not sure I see any use in the "Refresh button which de-activate and re-activate a profile, from the edit window" item.  
Settings would take effect immediately anyway, no need to refresh.

**Comment by Snoothy** [comment]
Remaining items have been moved to TODO
