### ISSUE TITLE
Design suggestions

### ISSUE THREAD

**Issue by spadino** [Snoothy/UCR#54]
- [ ] Allow Axis plugin to be created with one, two or three axes (linear, circular, spherical), which share the same settings.
- [ ] Chainable modifiers

**Comment by evilC** [comment]
At the moment, inputs are hard-wired into the plugin - ie you would have to have a 3-axis plugin, and just not use some of them if you do not want to.  
Not quite sure what you mean by "Chainable modifiers"

**Comment by Snoothy** [comment]
Plugins are currently designed to have a fixed input and output and is not trivial to change. Chainable modifiers are not really very descriptive, however, what explained before is something which has been considered but we have yet to find a suitable solution
