### ISSUE TITLE
Mouse to Axis feature

### ISSUE THREAD

**Issue by spadino** [Snoothy/UCR#55]
I see that there's no apparently any way to map a mouse to analog axis without losing the mouse itself. There's a way to have it be mapped without have it cease to work as a mouse?

**Comment by evilC** [comment]
If you have block enabled in the xml file, any binding will be blocked.  
There is currently no way to block on a per-input basis.  
We need to allow the front-end to specify blocking to the back-end for a specific binding, which will require a slight design change.

**Comment by Snoothy** [comment]
Intended functionality when the experimental Interception feature is used
