### ISSUE TITLE
Mouse to Axis / Delta to Axis not appearing in plugin list

### ISSUE THREAD

**Issue by XetrovTornado** [Snoothy/UCR#63]
Hello, I have UCR 0.6.0 downloaded and Interception installed. When I try to add a plugin, I cannot see a Mouse to Axis or Delta to Axis option. I am trying to map mouse movement to the right stick of an emulated Xbox controller.

![ucr screenshot](https://user-images.githubusercontent.com/23283029/50568050-b501f700-0cf0-11e9-9884-36cb3e6ca4cf.png)

**Comment by evilC** [comment]
This plugin is part of the [UCR-Plugins](https://github.com/HidWizards/UCR-Plugins) repo  - it does not ship with UCR
