### ISSUE TITLE
(Button to axis ) when you tap right and then leave it and then quickly tap left ( or any other combination) it stays in middle position for some time [ Solved] 

### ISSUE THREAD

**Issue by 94d33m** [Snoothy/UCR#66]
It stays in middle position for some time then goes to the corresponding direction. Because of this the character does not move instantaneously when going from left to right or up to down or vice versa

**Comment by Snoothy** [comment]
Please elaborate what plugin you're using and which devices you're trying to map to and from. This issue is not very informative

**Comment by evilC** [comment]
Also please clarify "Leave it" - do you mean "Keep holding right"?

**Comment by 94d33m** [comment]
@ Snoothy Using the interception and VigEm. I'm trying to map from keyboard button to Xbox axis (wasd to left stick axis).

@evilC By leave it I mean, stop pressing it. 

I'll upload a small vid to show clearly

**Comment by 94d33m** [comment]
Here, https://youtu.be/GH9nKzpLTHI and https://youtu.be/GfhcOsLjrvQ
Hope its clear what im trying to convey

**Comment by Snoothy** [comment]
If you're using two "Button to Axis" plugins, then you might end up in the middle position if you do the following:

1. Press left
2. Press right
3. Release left
Axis is now in the middle

You should use the other plugin "Button**s** to Axis" to avoid this behaviour

**Comment by 94d33m** [comment]
Alright man, gotcha, great work
