### ISSUE TITLE
Adding Button+AxisToAxis plugin

### ISSUE THREAD

**Issue by lomotkapa** [Snoothy/UCR#71]
It's will be really useful in sims with lot of axis.
Pressing button "A" and roll axis "A" on joystic will give output as axis 1 of virtual joystic, pressing another button "B" and roll same axis "A" on joystic will give output axis 2 of virtual joystic.
Roll axis "A" without pressing any buttons will give output as axis 3 of virtual joystic (by AxisToAxis plugin).
And will be grate to do checkbox for variants of using button - press and hold, or press and release,

**Comment by Snoothy** [comment]
There is a future planned feature to support this called: Filters
