### ISSUE TITLE
Xbox axis

### ISSUE THREAD

**Issue by NiggaInTheNight** [Snoothy/UCR#77]
What i need for binding X56 saitek/logitech to xbox axis? I mean do i need install something before use UCR? I try to create profile, ucr can see X56 axis, i can bind that to titan one axis and activate is successfull, but it didnt work in game. When i try to bind to ViGEm i have error:
DEBUG Activating profile: {Xbox} 
DEBUG Successfully populated subscription state 
DEBUG Subscribing output device: {Device:{ViGEm Xbox 360 Controller 1} Provider:{Core_ViGEm} Handle:{xb360} Num:{0}} 
ERROR Failed to activate profile successfully 
DS4 same error:
DEBUG Activating profile: {Xbox} 
DEBUG Successfully populated subscription state 
DEBUG Subscribing output device: {Device:{ViGEm DS4 Controller 1} Provider:{Core_ViGEm} Handle:{ds4} Num:{0}} 
ERROR Failed to activate profile successfully

**Comment by evilC** [comment]
What exactly are you trying to map to? A virtual Xbox controller (Software), or a Titan One device (Hardware)  
To use virtual xbox, you will need ViGEm installed.  
To use Titan One, you will need a Titan One dongle (A USB device)

**Comment by NiggaInTheNight** [comment]
I have x56 controller(hardware). I need emulate xbox axis.

>>To use virtual xbox, you will need ViGEm installed.
Its same driver like ucr on ahk? I ask because i had problem after install xbox driver in ahk ucr. I rollback system because when i run ucr my comp dont answer on any actions and idk how i can uninstall it without run ucr (rollback was successfull).

**Comment by evilC** [comment]
No, you are talking about the input device (The X56), I am talking about the output device (The xbox controller).  
How are you creating the virtual xbox controller?

**Comment by NiggaInTheNight** [comment]
How i must create that? By ViGEm? It same driver like on UCR-ahk version? I have bsod after install xbox driver on UCR-ahk. It same or not?

And i have problem with distribution system for ViGEm. Its extreme strange for win. Compile under win? I know what is it. 90% just didnt work with default make files, msys dont have new version of library, msvs just cant because it have error. Install ps? I not ready to install that crap and lose 3-4gb on system drive just for download signed version. Where is binary for download? Its a win-system =\

**Comment by evilC** [comment]
https://docs.vigem.org/#!vigem-bus-driver-installation.md

**Comment by NiggaInTheNight** [comment]
That binares must be installed in powershell ver 5. Powershell it very huge. Install MS Xbox 360 Accessories, Install PS for install ViGEm for connect to ucr? =\ As i say, i not ready lose 3-4 gb disk space (Powershell installation) on system drive for just download ViGEm. Can it be downloaded without PS?

**Comment by evilC** [comment]
Use the "Caveman Installation" linked at the top  

![](https://cdn.discordapp.com/attachments/498908920094523392/540215661234749462/unknown.png)

**Comment by NiggaInTheNight** [comment]
Lol. What reason for that instruction? Why dont distrib ViGEm + devcon + bat? It all what needed. I never understand that. I recommend include direct link on vJoy and ViGEm for avoid that problem, or include that in distrib. Thx for help.

**Comment by evilC** [comment]
I dunno why he did it like he did, he said earlier that he was going to be making an installer soon
