### ISSUE TITLE
1) Unable to load DLL 'Tobii.EyeX.Client.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

### ISSUE THREAD

**Issue by joki0924** [Snoothy/UCR#79]
http://prntscr.com/mhtia6

**Comment by hooty7734** [comment]
^ same

**Comment by hooty7734** [comment]
Same issue as stated above, tried multiple releases and all yielded the same result.

**Comment by ppenelon** [comment]
Same issue on Windows 10.

**Comment by evilC** [comment]
If you don't need Tobii Eye Tracker support, delete the folder `Providers\Core_Tobii_Interaction`  
The underlying problem is that you are missing some microsoft runtimes, but I am not entirely sure which ones - I think it is Visual C++ runtimes.

**Comment by evilC** [comment]
I think I found out what it was.

https://www.microsoft.com/en-us/download/details.aspx?id=30679

Please install this and tell me if it fixes the issue

**Comment by skiria8** [comment]
I installed the C++ runtimes but it didn't fix the issue. 
Where should the folder Providers\COre_Tobii_Interaction be located?

**Comment by evilC** [comment]
In your UCR folder  
I just made some code changes, in the next release UCR will not fail to load if one of the providers crashes on start

**Comment by Snoothy** [comment]
Should be fixed with release v0.8.0
