### ISSUE TITLE
Multimedia Key Input

### ISSUE THREAD

**Issue by archit9169** [Snoothy/UCR#80]
There is not option to select multimedia keys for input, like Volume_Up, Volume_Down, Browser_Home etc.
Hope this will be added soon.

**Comment by evilC** [comment]
Interception does not support Media keys via USB, only via PS/2.  
This is not likely to change in the near future, we have no replacement for Interception.

**Comment by superuser7777** [comment]
Are there any plans to support Media keys "out"?

**Comment by evilC** [comment]
This is not something that I can support. This would be part of the
Interception source code, to which I do not have access.
