### ISSUE TITLE
Keep last used plugin when adding new mapping.

### ISSUE THREAD

**Issue by DanTDBV** [Snoothy/UCR#85]
I have an enhancement suggestion, that I feel have the potential to make it easier, to use this very useful application.

Suggestion:
Have the Add plugin dialog keep the last used plugin, at least in the current session, instead of reverting to the Axes Range to Button, each time a new mapping is added.

Having up to 25 axes and 139 button and hat presses on 7 different devices to assign, makes it very timeconsuming and somewhat frustrating having to change it each time. 

It would also be very nice, if the output device dialog could keep the last used device.

Thank you very much for the effort that you put into this great project.

**Comment by Snoothy** [comment]
This is already addressed in the upcoming redesign using Material Design
