### ISSUE TITLE
Multiple Profiles Activated

### ISSUE THREAD

**Issue by Phenerium** [Snoothy/UCR#88]
I'm trying to use 3 keyboards for playing in Nintendo 64, so far i have 2 profiles working like a charm (the default windows keyboard is the 3rd controller) but i can only active one profile at a time. When i try to active another profile, the first one is deactivated. Is there a way to make this work? Am i missing something?

**Comment by Snoothy** [comment]
It is by design that you can only have one profile active at a time. However, activating a nested profile will also activate all of its parents. So you either have to put everything in one profile or make use of nested profiles
