### ISSUE TITLE
Changes to EditBoxes do not take effect until they lose focus

### ISSUE THREAD

**Issue by evilC** [Snoothy/UCR#9]
Found in v0.3.1

1. Add a new mapping
2. Add a ButtonToAxis plugin
3. Bind Inputs / Outputs
4. Leave "Range Target" on default of 100
5. Activate profile
6. Axis deflects to full on press of button
7. Deactivate profile
8. Type 50 into Target Box
9. Activate Profile
10. Axis still deflects to full (BUG)
11. Deactivate profile
12. Click somewhere else so editbox loses focus (eg click Mapping)
13. Activate Profile
14. Axis now correctly deflects to 50% on press of button

**Comment by Snoothy** [comment]
The text field doesn't lose focus when clicking menus, should be fixed

**Comment by evilC** [comment]
Root cause is that when you click activate in step 9, the control should lose focus

**Comment by evilC** [comment]
Not a bug, by design
