### ISSUE TITLE
Delta To Axis absolute mode super jittery

### ISSUE THREAD

**Issue by xx-Maixxi-xx** [Snoothy/UCR#92]
I have this weird issue, i dont know if this is intended but however. i have made a DS4 emulated(obvious) controller in the hopes that i can use it with PS now (which is a streaming service). i am using HTML5 gamepad tester to help me set this DS4 up, and i've came into this problem where the absolute mode is extremely jittery and janky. however when the said mode is off, the joystick moves freely with my mouse movements, as compared to the absolute mode, it seems that the joystick is on some sort of grid.. hopefully i explained this well.

**Comment by xx-Maixxi-xx** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/49469681/55857094-35c75f00-5b3a-11e9-9ad3-fa780aa8e54d.gif)

**Comment by xx-Maixxi-xx** [comment]
I have uninstalled interception and ViGem and reinstalled them... nothing still the same problem. i have no clue how to fix this issue

**Comment by Snoothy** [comment]
This is usually the case if you are running your mouse at 1000Hz, try lowering this. For further issues, please create them at the repo for experimental plugins
