### ISSUE TITLE
The profile could not be activated

### ISSUE THREAD

**Issue by Salvobioinfo** [Snoothy/UCR#96]
I tried to configure thrustmaster Hotas X with xbox controller, but after i have done the profile when I want to activate it didn't go, I get thise errore message: the profile could not be activated, see the log for more details ... another thing is that how to save created profile? The save button is not active.
[2019-04-21.log](https://github.com/Snoothy/UCR/files/3101499/2019-04-21.log)

**Comment by evilC** [comment]
Looks like ViGEm is not installed correctly.  
Try using the [new installer](https://github.com/ViGEm/ViGEmBus/releases/latest)

**Comment by Salvobioinfo** [comment]
Yes the installation of Vgem failed. Now all work fine.
