### ISSUE TITLE
Add input parameters for controlling UCR with EDS

### ISSUE THREAD

**Issue by SilverbackPrime** [Snoothy/UCR#97]
i.e. something along the lines of:

`C:\ArcadeMachine\UCR> UCR.exe -"[MyProfile]" -[a|d]`

**Comment by Snoothy** [comment]
It is possible to launch profiles through parameters: `UCR.exe -p "Myprofile"`
Nested search is possible using comma: `UCR.exe -p "My emulator, My first game category, Some game"`

**Comment by Snoothy** [comment]
A more detailed description can now be found on the Wiki: https://github.com/Snoothy/UCR/wiki/Command-line-arguments
