### ISSUE TITLE
Disabling/Hiding input devices?

### ISSUE THREAD

**Issue by Jabster28** [Snoothy/UCR#99]
Hello,

I was using this program to emulate an Xbox Controller with two JoyCons, which worked well. However, the application that I was using detected not only the Virtual Xbox Controller, but also the JoyCons. Would it be possible to hide or disable the input group from other applications?

**Comment by evilC** [comment]
See [HidGuardian](https://github.com/ViGEm/HidGuardian)  
UCR will auto-whitelist with HG

**Comment by Snoothy** [comment]
You can also use Steam to hide your joycon controllers in the latest Steam beta if you are playing the game through Steam
